// Hangman word bank. Categories hold single words and short phrases (spaces,
// hyphens and apostrophes are shown for free). EXTRA is a pile of everyday words
// that, together with every single word above, feeds Evil mode and the bots.

const list = (s) => s.trim().split(/\s*\n\s*|\s*,\s*/).filter(Boolean);

export const CATEGORIES = [
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🦊',
    words: list(`
      aardvark, alligator, alpaca, anteater, antelope, armadillo, badger, beaver, bison, buffalo, butterfly,
      camel, caterpillar, chameleon, cheetah, chicken, chimpanzee, chipmunk, cobra, cougar, coyote, crab,
      crocodile, dolphin, donkey, dragonfly, eagle, elephant, falcon, ferret, flamingo, fox, frog, gazelle,
      gecko, giraffe, goldfish, gorilla, grasshopper, hamster, hedgehog, hippopotamus, hummingbird, hyena,
      iguana, jaguar, jellyfish, kangaroo, koala, ladybug, lemur, leopard, lion, llama, lobster, meerkat,
      mongoose, moose, mosquito, octopus, ostrich, otter, owl, panda, panther, parrot, peacock, pelican,
      penguin, platypus, porcupine, rabbit, raccoon, rattlesnake, reindeer, rhinoceros, salamander, scorpion,
      seahorse, shark, skunk, sloth, snail, squirrel, starfish, stingray, swan, tarantula, tiger, toucan,
      turtle, vulture, walrus, warthog, weasel, whale, wolf, wolverine, wombat, woodpecker, yak, zebra,
      polar bear, sea lion, killer whale, bald eagle, guinea pig, honey badger, red panda, blue whale
    `),
  },
  {
    id: 'food',
    name: 'Food',
    emoji: '🍕',
    words: list(`
      avocado, bagel, banana, barbecue, biscuit, blueberry, broccoli, brownie, burrito, butter, cabbage,
      cantaloupe, caramel, carrot, cauliflower, cheddar, cheeseburger, cherry, chocolate, cinnamon, coconut,
      cookie, croissant, cucumber, cupcake, doughnut, dumpling, eggplant, enchilada, falafel, garlic, ginger,
      granola, grapefruit, guacamole, hamburger, hazelnut, honey, hotdog, jalapeno, kiwi, lasagna, lemonade,
      lettuce, lobster, macaroni, mango, marshmallow, meatball, milkshake, muffin, mushroom, mustard, nachos,
      noodles, oatmeal, omelet, onion, pancake, papaya, pasta, peanut, pepperoni, pickle, pineapple, pizza,
      popcorn, potato, pretzel, pudding, pumpkin, quesadilla, raspberry, ravioli, salad, salsa, sandwich,
      sausage, smoothie, spaghetti, spinach, strawberry, sushi, taco, tomato, tortilla, waffle, watermelon,
      zucchini, french fries, ice cream, hot sauce, apple pie, mac and cheese, peanut butter, fried rice,
      chicken nuggets, garlic bread, maple syrup, cotton candy, birthday cake, scrambled eggs
    `),
  },
  {
    id: 'places',
    name: 'Places',
    emoji: '🗺️',
    words: list(`
      airport, amusement park, aquarium, bakery, beach, bowling alley, bridge, campground, canyon, castle,
      cathedral, cinema, desert, farm, forest, garage, glacier, hospital, hotel, island, jungle, laboratory,
      library, lighthouse, mall, museum, observatory, palace, playground, pyramid, rainforest, restaurant,
      school, skatepark, stadium, subway, supermarket, swamp, theater, train station, volcano, waterfall,
      zoo, australia, brazil, canada, egypt, france, germany, greece, iceland, india, ireland, italy, japan,
      kenya, mexico, morocco, new zealand, norway, peru, portugal, scotland, spain, sweden, switzerland,
      thailand, vietnam, amsterdam, barcelona, chicago, dubai, hollywood, las vegas, london, los angeles,
      miami, new york, paris, rome, san francisco, sydney, tokyo, toronto, venice, grand canyon, hawaii,
      alaska, antarctica, sahara, amazon, mount everest, niagara falls
    `),
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    words: list(`
      archery, badminton, baseball, basketball, biathlon, bobsled, bowling, boxing, canoeing, cheerleading,
      cricket, croquet, curling, cycling, darts, diving, dodgeball, fencing, football, frisbee, golf,
      gymnastics, handball, hockey, hurdles, javelin, judo, karate, kayaking, lacrosse, marathon, motocross,
      paintball, pickleball, ping pong, polo, rowing, rugby, sailing, skateboarding, skiing, snowboarding,
      soccer, softball, sprinting, squash, surfing, swimming, taekwondo, tennis, trampoline, triathlon,
      volleyball, wakeboarding, water polo, weightlifting, wrestling, rock climbing, figure skating,
      mini golf, slam dunk, home run, touchdown, hat trick, penalty kick, hole in one, free throw,
      goalkeeper, referee, quarterback, pitcher, scoreboard, trophy, medal, stopwatch, whistle, overtime
    `),
  },
  {
    id: 'home',
    name: 'Around the House',
    emoji: '🛋️',
    words: list(`
      armchair, bathtub, bedroom, blanket, bookshelf, broom, bucket, candle, carpet, ceiling, chandelier,
      closet, couch, cupboard, curtain, cushion, dishwasher, doorbell, drawer, dresser, dustpan, faucet,
      fireplace, freezer, garage, hammer, hanger, kettle, keyboard, kitchen, ladder, lamp, laundry, lightbulb,
      mailbox, mattress, microwave, mirror, mop, napkin, oven, pantry, pillow, plunger, refrigerator, remote,
      rug, scissors, shampoo, shower, sink, sofa, spatula, sponge, stairs, stapler, stove, suitcase, table,
      teapot, television, toaster, toilet, toothbrush, toothpaste, towel, vacuum, wardrobe, washing machine,
      window, coffee table, alarm clock, frying pan, ceiling fan, picture frame, light switch, welcome mat,
      laundry basket, rocking chair, bunk bed, smoke detector, garden hose
    `),
  },
  {
    id: 'jobs',
    name: 'Jobs',
    emoji: '👩‍🚀',
    words: list(`
      accountant, architect, artist, astronaut, athlete, baker, barber, bartender, carpenter, cashier, chef,
      chemist, coach, dentist, designer, detective, doctor, electrician, engineer, farmer, firefighter,
      florist, gardener, hairdresser, journalist, judge, lawyer, librarian, lifeguard, magician, mechanic,
      musician, nurse, paramedic, pharmacist, photographer, pilot, plumber, police officer, professor,
      programmer, scientist, sculptor, singer, surgeon, tailor, teacher, translator, veterinarian, waiter,
      zookeeper, flight attendant, bus driver, game designer, personal trainer, real estate agent,
      software engineer, mail carrier, park ranger, news anchor, ballet dancer, deep sea diver, comedian,
      archaeologist, meteorologist, locksmith, beekeeper, blacksmith, lumberjack, chauffeur
    `),
  },
  {
    id: 'nature',
    name: 'Nature',
    emoji: '🌿',
    words: list(`
      avalanche, blizzard, boulder, breeze, canyon, cliff, cloud, coral, crystal, daisy, dandelion, desert,
      earthquake, eclipse, fern, fog, forest, fossil, geyser, glacier, hailstorm, hurricane, iceberg, island,
      lagoon, lava, lightning, meadow, moss, mountain, mushroom, oak tree, ocean, orchid, pebble, petal,
      pinecone, puddle, rainbow, river, seashell, snowflake, stream, sunflower, sunrise, sunset, thunder,
      tornado, tulip, tundra, valley, volcano, waterfall, wildflower, willow, sand dune, northern lights,
      full moon, shooting star, rain cloud, palm tree, maple leaf, tide pool, coral reef, cactus, bamboo,
      redwood, evergreen, sapling, waterlily, sunbeam, rainstorm, monsoon, drizzle, frost, dew
    `),
  },
  {
    id: 'phrases',
    name: 'Phrases',
    emoji: '💬',
    words: list(`
      better late than never, break a leg, piece of cake, under the weather, hit the sack, spill the beans,
      once in a blue moon, the best of both worlds, bite the bullet, cost an arm and a leg, actions speak louder than words,
      every cloud has a silver lining, back to square one, call it a day, cut to the chase, easy does it,
      get out of hand, go the extra mile, hang in there, in the same boat, it takes two to tango,
      keep your chin up, let the cat out of the bag, no pain no gain, on cloud nine, on thin ice,
      practice makes perfect, rain or shine, the ball is in your court, time flies, under the radar,
      when pigs fly, you can say that again, a blessing in disguise, beat around the bush, cold feet,
      down to earth, fish out of water, head over heels, last but not least, out of the blue,
      read between the lines, see eye to eye, the early bird gets the worm, two peas in a pod,
      whole nine yards, game over, high five, good luck, sweet dreams, see you later, happy birthday,
      thank you very much, no way, just kidding, all hands on deck, against the clock, ready set go
    `),
  },
  {
    id: 'music',
    name: 'Music',
    emoji: '🎸',
    words: list(`
      accordion, bagpipes, banjo, bass guitar, bassoon, bongo, cello, chorus, clarinet, concert, conductor,
      cymbal, drumstick, drum kit, electric guitar, flute, guitar, harmonica, harp, headphones, jazz, karaoke,
      keyboard, lullaby, lyrics, mandolin, maracas, melody, metronome, microphone, orchestra, piano, playlist,
      rhythm, saxophone, songwriter, soundtrack, speaker, symphony, synthesizer, tambourine, trombone, trumpet,
      tuba, ukulele, violin, xylophone, album, encore, festival, record player, rock and roll, hip hop,
      country music, opera, reggae, choir, duet, solo, tempo, chord, harmony, bass drop, love song,
      music video, radio station, sheet music, treble clef, grand piano, standing ovation
    `),
  },
  {
    id: 'space',
    name: 'Space',
    emoji: '🪐',
    words: list(`
      asteroid, astronaut, astronomy, black hole, comet, constellation, cosmos, crater, eclipse, galaxy,
      gravity, jupiter, mars, mercury, meteor, meteorite, milky way, moon, nebula, neptune, orbit, planet,
      pluto, rocket, satellite, saturn, solar system, space station, spaceship, star, sun, supernova,
      telescope, universe, uranus, venus, alien, launch pad, lunar module, mission control, moon landing,
      big bang, dwarf planet, solar flare, light year, gravity well, zero gravity, space suit, flying saucer,
      shooting star, big dipper, north star, red planet, rings of saturn, countdown, liftoff, cosmonaut, rover,
      spacewalk, starlight, sunspot, wormhole, quasar, pulsar, exoplanet, observatory
    `),
  },
  {
    id: 'movies',
    name: 'At the Movies',
    emoji: '🎬',
    words: list(`
      action hero, blockbuster, box office, cartoon, cinema, comedy, costume, director, documentary, drama,
      fantasy, horror, villain, superhero, sequel, trailer, popcorn, premiere, red carpet, screenplay,
      soundtrack, special effects, stunt double, plot twist, happy ending, cliffhanger, movie star, animation,
      dinosaur, robot, wizard, dragon, pirate, ninja, zombie, vampire, werewolf, mermaid, unicorn, spaceship,
      time machine, treasure map, haunted house, secret agent, car chase, magic wand, invisibility cloak,
      evil twin, sidekick, mad scientist, talking animal, alien invasion, final battle, credits, intermission,
      matinee, film festival, award show, movie night, director's cut, behind the scenes
    `),
  },
  {
    id: 'kids',
    name: 'Easy Words',
    emoji: '🧸',
    words: list(`
      apple, ball, balloon, banana, bear, bike, bird, boat, book, bubble, bunny, cake, candy, car, castle,
      cat, chair, clock, cloud, cookie, cow, crayon, cup, dog, doll, dragon, drum, duck, egg, fish, flower,
      frog, game, gift, hat, horse, house, juice, kite, lamp, lion, milk, monkey, moon, mouse, music, nest,
      owl, panda, park, party, pig, pizza, puppy, rain, robot, rocket, sandwich, school, shoe, sock, star,
      sun, swing, teddy, tiger, toy, train, tree, truck, turtle, water, whale, zebra, rainbow, unicorn,
      snowman, pirate, jelly, slide, smile, pencil, sticker, puzzle, blanket
    `),
  },
];

export const EXTRA = list(`
  able, about, above, absent, accept, account, across, action, active, actor, adult, advice, afraid, after,
  again, against, agent, agree, ahead, alarm, album, alert, alive, allow, almost, alone, along, already,
  always, amount, ancient, angel, anger, angle, angry, animal, answer, anyone, anything, appear, apron,
  arena, argue, arrive, arrow, artist, aside, asleep, attack, attic, autumn, avoid, awake, award, aware,
  awful, baby, back, bacon, badge, bake, balance, bamboo, band, bank, barrel, basic, basket, battle,
  beard, beauty, become, before, begin, behind, being, believe, belong, below, bench, beside, better,
  between, beyond, bicycle, bigger, billion, binder, birth, bitter, black, blade, blame, blank, blast,
  blend, blind, block, blood, bloom, board, body, bonus, border, borrow, bottle, bottom, bounce, bowl,
  brain, branch, brave, bread, break, brick, bride, brief, bright, bring, broad, broken, brother, brush,
  bubble, budget, build, bullet, bundle, burger, burst, button, cabin, cable, cactus, camera, canal,
  cannon, canvas, carbon, career, cargo, carpet, carry, casual, catch, cause, cellar, center, cereal,
  chain, chalk, chance, change, chapter, charge, charm, chart, chase, cheap, check, cheek, cheese,
  chess, chest, chief, child, chimney, choice, choose, circle, circus, city, claim, class, clean, clear,
  clever, client, climb, clinic, close, cloth, clown, coach, coast, coffee, collar, color, column, combat,
  comfort, common, copper, corner, cotton, cough, count, county, couple, courage, course, cousin, cover,
  crack, craft, crane, crash, crazy, cream, credit, crew, crime, crisp, crowd, crown, cruel, crumb, crush,
  curve, custom, cycle, daily, damage, dance, danger, daring, dark, daughter, dealer, debate, decade,
  decide, deep, defend, degree, delay, demand, depth, desert, design, desk, detail, device, diamond,
  diary, dinner, direct, dirty, doctor, dollar, domain, double, dozen, draft, drama, dream, dress, drift,
  drink, drive, dust, duty, eager, early, earth, easily, edge, effect, effort, eight, either, elbow,
  elder, eleven, empty, enemy, energy, engine, enjoy, enough, enter, entry, equal, error, escape, event,
  every, exact, exist, expert, extra, fabric, face, fact, fade, faith, false, fame, family, famous,
  fancy, fault, favor, feast, feather, fence, fever, field, fifty, fight, figure, final, finger, finish,
  first, flag, flame, flash, fleet, flight, float, floor, flour, fluid, focus, folder, follow, force,
  forest, forget, formal, fortune, forum, forward, frame, fresh, friend, fringe, front, frozen, fruit,
  future, gallery, gamble, garden, gather, gentle, giant, glass, global, glove, glow, goal, golden,
  govern, grace, grade, grain, grand, grant, grape, grass, grave, great, green, grief, grill, ground,
  group, growth, guard, guess, guest, guide, guilty, guitar, habit, hammer, handle, happen, happy,
  harbor, hardly, harvest, hazard, health, heart, heavy, height, hello, helmet, hidden, highway, history,
  hobby, holiday, hollow, honest, hope, horizon, horror, hunger, hunter, hurry, idea, image, impact,
  income, indoor, infant, injury, inner, insect, inside, island, ivory, jacket, jelly, jewel, joint,
  journey, judge, jungle, junior, justice, kidney, kingdom, kitchen, knife, knock, label, ladder, laptop,
  large, laser, laugh, launch, layer, leader, league, learn, leather, legal, legend, lemon, length,
  lesson, letter, level, liberty, light, limit, linen, liquid, listen, little, living, lizard, local,
  lock, lonely, loose, lounge, lovely, lucky, lumber, lunch, luxury, machine, magic, magnet, maiden,
  major, maker, manner, marble, margin, market, master, match, matter, meadow, medal, member, memory,
  mental, mention, merit, message, metal, middle, mighty, million, minute, mirror, mission, mixture,
  model, modern, moment, money, monster, month, moral, morning, mother, motion, motor, mountain, mouth,
  movie, muscle, myself, mystery, narrow, nation, native, nature, needle, nephew, nerve, network, never,
  night, noble, noise, normal, north, notice, novel, number, object, ocean, office, olive, orange, orbit,
  order, origin, outdoor, outer, oxygen, packet, paddle, palace, panel, paper, parade, parent, parrot,
  partner, party, patch, patient, pattern, pause, peace, pencil, people, pepper, period, person, phone,
  photo, piano, picnic, picture, piece, pilot, pirate, place, plain, planet, plaster, plastic, plate,
  pocket, poem, poetry, point, polite, pond, popular, portrait, potato, powder, power, praise, prefer,
  pretty, price, pride, prince, prison, prize, problem, profit, project, proof, proud, public, pulse,
  punch, pupil, puppet, purple, puzzle, quarter, queen, question, quick, quiet, quilt, quote, rabbit,
  racket, radar, radio, random, rapid, rather, reach, ready, reason, record, region, remote, repair,
  report, rescue, result, return, reward, ribbon, rider, riddle, right, rigid, ripple, ritual, rival,
  river, robot, rocket, rough, round, route, royal, rubber, ruler, rumor, rural, saddle, safety, sailor,
  salmon, sample, sauce, scale, scarf, scene, scheme, scout, screen, script, search, season, second,
  secret, select, senior, sense, series, settle, seven, shadow, shallow, shape, share, sharp, shelf,
  shell, shield, shift, shine, shirt, shock, short, shoulder, shout, shrimp, sight, signal, silent,
  silk, silver, simple, single, sister, skill, skirt, sleep, slice, slight, slogan, small, smart, smile,
  smoke, smooth, snack, snake, social, soldier, solid, sound, south, space, spark, speak, special,
  speech, speed, spider, spirit, splash, spoon, sport, spray, spring, square, stable, staff, stage,
  stamp, stand, start, steady, steel, stick, still, stone, storm, story, stove, straw, street, strike,
  string, strong, studio, stuff, style, sudden, sugar, summer, summit, sunny, super, supply, sure,
  surface, survey, sweet, swift, switch, symbol, system, table, tablet, talent, target, taste, temple,
  tender, tennis, tent, theory, thick, thief, thing, think, thirty, thread, three, throat, throne, thumb,
  ticket, tiger, timber, tired, title, toast, today, token, tomato, tongue, tonight, tooth, topic,
  torch, total, touch, tough, tower, track, trade, traffic, travel, treat, trend, trial, tribe, trick,
  trophy, truck, trust, truth, tunnel, twelve, twenty, twist, uncle, under, unique, unit, update, upper,
  urban, useful, valley, value, velvet, venture, verse, vessel, video, village, violet, virtue, vision,
  visit, visual, vital, voice, volume, voyage, wagon, waiter, wallet, wander, warm, warning, wealth,
  weapon, weather, wedding, weekend, weight, wheat, wheel, whisper, white, whole, widow, width, wild,
  window, winner, winter, wisdom, witness, woman, wonder, wooden, worker, world, worry, worth, wrist,
  writer, yellow, young, youth, zebra, zipper, zone
`);
